name: flutter_bloc_base
description: Flutter Bloc Base
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.0.1
  # Network
  dio: ^5.2.1+1
  socket_io_client: ^2.0.3+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.1

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3

  # Utils
  get_it: ^7.6.4
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  connectivity_plus: ^4.0.2
  top_snackbar_flutter: ^3.1.0
  bot_toast: ^4.0.4
  form_field_validator: ^1.1.0
  enum_to_string: ^2.0.1
  google_fonts: ^4.0.3

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.0
  just_the_tooltip: ^0.0.12
  package_info_plus: ^8.0.0
  retry: ^3.1.2
  go_router: ^14.2.0
  intl: ^0.19.0
  flutter_localization: ^0.2.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.0
  flutter_gen_runner: ^5.6.0
  freezed: ^2.5.2
  device_info_plus: ^10.1.0
  url_launcher: ^6.3.0

# Config generate when build
flutter_gen:
  output: lib/gen/
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true
    flare_flutter: true

  assets:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/logo/